### PR TITLE
Fixing and implementing affine aligners

### LINKED ISSUE #40: Check affine aligner

### PR DESCRIPTION
**Pull request by PoslavskySV**
This PR include:

- fixes for Aligner#alignGlobalAffine
- fixes for Aligner#alignLocalAffine
- fixes for AlignerCustom#alignAffineSemiLocalLeft0
- implementation of AlignerCustom#alignAffineSemiLocalRight0
- fixes for BandedAffineAligner

This fixes #40

### CODE REVIEW

File: src/main/java/com/milaboratory/core/alignment/Aligner.java [hunk 1]
```diff
@@ -396,105 +439,114 @@ else if (i1 == -1) {
...
+                        matrix.get(i - 1, j) + gapOpenPenalty + gapExtensionPenalty,
+                        gapIn2.get(i - 1, j) + gapExtensionPenalty));
+
+                matrix.set(i, j, max(0,
+                        matrix.get(i - 1, j - 1) +
+                                scoring.getScore(seq1.codeAt(i - 1), seq2.codeAt(j - 1)),
+                        gapIn2.get(i, j),
+                        gapIn1.get(i, j)));
+
+                if (matrix.get(i, j) > max && matrix.get(i, j) != 0) {
```
Comment (dbolotin) [inline src/main/java/com/milaboratory/core/alignment/Aligner.java]: `!= 0` ?

File: src/main/java/com/milaboratory/core/alignment/Aligner.java [hunk 2]
```diff
@@ -396,105 +439,114 @@ else if (i1 == -1) {
...
+        int i, j;
+        for (i = 1; i < size1; ++i)
+            gapIn1.set(i, 0, MIN_VALUE);
 
-        for (int i = 0; i < size1; i++)
-            alignYTOGapAfterX[i * size2] = -10000;
+        for (j = 1; j < size2; ++j)
+            gapIn2.set(0, j, MIN_VALUE);
 
         int max = -1;
```
Comment (dbolotin) [inline src/main/java/com/milaboratory/core/alignment/Aligner.java]: ` = 0` ?
